/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultListModel; 
import java.io.File;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class mainForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainForm.class.getName());
    private final String tes = "data-tugas.txt";
    private final String tess = "deadline.txt"; 

    String deadline;
    DefaultListModel<String> model = new DefaultListModel<>();
    DefaultListModel<String> modelDua = new DefaultListModel<>();
    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        jList1.setModel(model);
        jList1.addListSelectionListener(e -> {
        int index = jList1.getSelectedIndex();
        if (index != -1 && index < modelDua.getSize()) {
            deadlineText.setText("Deadline : " + modelDua.get(index));
        }
        if (index == -1) {
            deadlineText.setText("");
        }
    });

        muatData();
        muatDataDua();
        addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
//            simpanData(); // Panggil method simpan (Langkah 5)
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        start = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        toDoList = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        deadlineText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 248, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(655, 400));

        jList1.setBorder(new javax.swing.border.MatteBorder(null));
        jList1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jList1);

        tambah.setBackground(new java.awt.Color(102, 51, 0));
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("✚ Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        System.out.println("tegar gacor 123"); //hapus ini setelah itu
        hapus.setBackground(new java.awt.Color(102, 51, 0));
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("🗑 Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        start.setBackground(new java.awt.Color(102, 51, 0));
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("▶ Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(102, 51, 0));
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("🖉 Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(90, 130, 126));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        toDoList.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        toDoList.setForeground(new java.awt.Color(255, 255, 255));
        toDoList.setText("To-Do-List");
        toDoList.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(toDoList, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(toDoList)
                .addGap(19, 19, 19))
        );

        deadlineText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deadlineText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(deadlineText, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {                                       

        javax.swing.JTextField inputKegiatan = new javax.swing.JTextField();
        javax.swing.JTextField inputDeadline = new javax.swing.JTextField();

    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(2, 2));
    panel.add(new javax.swing.JLabel("Nama Kegiatan:"));
    panel.add(inputKegiatan);
    panel.add(new javax.swing.JLabel("Deadline (dd/MM/yyyy):"));
    panel.add(inputDeadline);

          int result = javax.swing.JOptionPane.showConfirmDialog(
            this,
            panel,
            "Tambah Tugas Baru",
            javax.swing.JOptionPane.OK_CANCEL_OPTION,
            javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (result == javax.swing.JOptionPane.OK_OPTION) {
        String kegiatan = inputKegiatan.getText().trim();
        String deadlineInput = inputDeadline.getText().trim();

        LocalDate parsedDeadline;
        try {
            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            parsedDeadline = LocalDate.parse(deadlineInput, format);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Deadline harus berformat dd/MM/yyyy\nContoh: 07/12/2025",
                "Format Salah", JOptionPane.ERROR_MESSAGE);
            return;
        }

        deadline = parsedDeadline.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        if (!kegiatan.isEmpty() && !deadline.isEmpty()) {
            model.addElement(kegiatan);
            modelDua.addElement(deadline);
            simpanDataDua();
            simpanData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Isi kegiatan dan deadline dengan lengkap!");
        }
    }
    }                                      
    
    private void muatData() {
    java.io.File file = new java.io.File("data-tugas.txt");

    if (!file.exists()) {
        return; 
    }
    try (java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader(file))) {
        String line;
        while ((line = reader.readLine()) != null) {
            model.addElement(line);
        }
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal memuat data: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void simpanDataDua() {
        try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter(tess))) {
        for (int i = 0; i < modelDua.getSize(); i++) {
            writer.write(modelDua.getElementAt(i));
            writer.newLine();
        }
        
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal menyimpan data: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }
    
    private void muatDataDua() {
    File file = new File(tess);

    if (!file.exists()) return;

    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
        String line;
        while ((line = reader.readLine()) != null) {
            modelDua.addElement(line);
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Gagal memuat deadline: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    
    private void simpanData() {
    try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter(tes))) {
        
        for (int i = 0; i < model.getSize(); i++) {
            writer.write(model.getElementAt(i));
            writer.newLine();
        }
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal menyimpan data: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
    
    public int getIndex(){
        return jList1.getSelectedIndex();
    }
   
    private void startActionPerformed(java.awt.event.ActionEvent evt) {                                      
     int index = jList1.getSelectedIndex();

    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Pilih tugas dulu sebelum mulai Pomodoro!");
        return;
    }

    String tugasDipilih = model.get(index);
    String deadlineDipilih = modelDua.get(index);

    pomodoroForm pomodoro1 = new pomodoroForm(index, this);
    pomodoro1.setVisible(true);
    this.setVisible(false);
    }                                     

    public void hapusTugas(int index) {
    if (index >= 0 && index < model.getSize()) {
        model.remove(index);
    }
          simpanData();
}
    
    public void hapusDeadline(int index) {
    if (index >= 0 && index < model.getSize()) {
        modelDua.remove(index);
    }
     if (index >= 0 && index < modelDua.getSize()) {
        modelDua.remove(index);
        simpanDataDua();
    }
          simpanDataDua();
}
    
    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {                                      
        int index = jList1.getSelectedIndex();
        if (index != -1) {
            model.remove(index);
            modelDua.remove(index);
        }
         if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih tugas yang ingin dihapus!",
                "Tidak ada tugas dipilih",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
        simpanData();
        simpanDataDua();
    }                                     

    private void editActionPerformed(java.awt.event.ActionEvent evt) {                                     
    int index = jList1.getSelectedIndex();

    if (index == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Pilih tugas yang ingin diedit!",
                "Tidak ada tugas dipilih",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String tugasLama = model.getElementAt(index);
    String oldDeadline = modelDua.getElementAt(index);

    String tugasBaru = javax.swing.JOptionPane.showInputDialog(
            this,
            "Edit tugas:",
            tugasLama
    );
    
    String newDeadline = javax.swing.JOptionPane.showInputDialog(
        this, 
        "Masukkan deadline baru (format: dd/MM/yyyy):", 
        oldDeadline
    );

    if (tugasBaru != null && !tugasBaru.trim().isEmpty()) {
        model.set(index, tugasBaru.trim());
    }
 
    
        LocalDate parsedDeadline;
    try {
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        parsedDeadline = LocalDate.parse(newDeadline.trim(), format);
        modelDua.set(index, newDeadline.trim());
        deadlineText.setText("Deadline : " + modelDua.get(index));

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Deadline harus berformat dd/MM/yyyy\nContoh: 07/12/2025",
                "Format Salah", JOptionPane.ERROR_MESSAGE);
        return; // hentikan proses edit
    }
    
            simpanData(); 
            simpanDataDua(); 
    }                                    

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainForm().setVisible(true));
    }
    ArrayList<String> daftar = new ArrayList<>();
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel deadlineText;
    public static javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton start;
    public static javax.swing.JButton tambah;
    private javax.swing.JLabel toDoList;
    // End of variables declaration                   

   public javax.sound.sampled.Clip mainkanSuara() {
    try {
        File soundFile = new File("alrm.wav");

        if (soundFile.exists()) {

            AudioInputStream audioInput = AudioSystem.getAudioInputStream(soundFile);
            
            Clip clip = AudioSystem.getClip();
            
            clip.open(audioInput);
            clip.loop(100);
            return clip;
            
        } else {
            System.out.println("File suara tidak ditemukan: " + "alrm.wav");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return null;
}
}