/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class pomodoroForm extends javax.swing.JFrame {
    
    private final int indexTugas;
    private final mainForm mainFormRef;
    
    public pomodoroForm(int indexTugas, mainForm mainFormRefa) {
    initComponents();
    this.indexTugas = indexTugas;
    this.mainFormRef = mainFormRefa;
        
    timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
            
            
                totalDetik--;
            
            
                updateTimerDisplay();
            
            
                if (totalDetik <= 0) {
                    timer.stop();
                    isRunning = false;
                    javax.sound.sampled.Clip player = mainFormRef.mainkanSuara();
                    btnStartPause.setText("Start");
                    lblTimerDisplay.setText("00:00");
                    javax.swing.JOptionPane.showMessageDialog(rootPane, "Waktu Habis!");
                    if (player != null) {
                        player.stop();
                        player.close();
                    }
                }
            }
        });
    
    
    
    
    if (indexTugas != -1 && mainFormRef.model.getSize() > indexTugas) {
             String namaTugas = mainFormRef.model.getElementAt(indexTugas);
             listtt.setText(namaTugas);
        }

}
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pomodoroForm.class.getName());
    private javax.swing.Timer timer;
    private int totalDetik;
    private boolean isRunning = false;

    /**
     * Creates new form pomodoroForm
     */

    private void updateTimerDisplay() {
    int menit = totalDetik / 60;
    int detik = totalDetik % 60;
    
    String displayText = String.format("%02d:%02d", menit, detik);
    
    lblTimerDisplay.setText(displayText);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblTimerDisplay = new javax.swing.JLabel();
        txtMenit = new javax.swing.JTextField();
        txtDetik = new javax.swing.JTextField();
        btnStartPause = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        toDoList = new javax.swing.JLabel();
        listtt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(254, 248, 238));
        jPanel2.setForeground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(665, 400));

        back.setBackground(new java.awt.Color(102, 51, 0));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(185, 212, 170));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        lblTimerDisplay.setFont(new java.awt.Font("Rockwell", 1, 80)); // NOI18N
        lblTimerDisplay.setForeground(new java.awt.Color(255, 255, 255));
        lblTimerDisplay.setText("00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTimerDisplay)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTimerDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        txtMenit.setBackground(new java.awt.Color(185, 212, 170));
        txtMenit.setForeground(new java.awt.Color(255, 255, 255));
        txtMenit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMenitActionPerformed(evt);
            }
        });

        txtDetik.setBackground(new java.awt.Color(185, 212, 170));
        txtDetik.setForeground(new java.awt.Color(255, 255, 255));
        txtDetik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDetikActionPerformed(evt);
            }
        });

        btnStartPause.setBackground(new java.awt.Color(102, 51, 0));
        btnStartPause.setForeground(new java.awt.Color(255, 255, 255));
        btnStartPause.setText("Start");
        btnStartPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartPauseActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(102, 51, 0));
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setText(" Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText(":");

        btnSelesai.setBackground(new java.awt.Color(102, 51, 0));
        btnSelesai.setForeground(new java.awt.Color(255, 255, 255));
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(90, 130, 126));

        toDoList.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        toDoList.setForeground(new java.awt.Color(255, 255, 255));
        toDoList.setText("POMODORO");
        toDoList.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(toDoList, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(toDoList)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        listtt.setText("Nama tugas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                        .addComponent(btnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listtt)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(txtMenit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDetik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(btnStartPause, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMenit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStartPause)
                            .addComponent(reset))
                        .addGap(97, 97, 97))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listtt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(back))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void backActionPerformed(java.awt.event.ActionEvent evt) {                                     
        mainForm mainForm1 = new mainForm();
        mainForm1.setVisible(true);
        this.dispose();
    }                                    

    private void btnStartPauseActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (isRunning) {
        timer.stop();
        isRunning = false;
        btnStartPause.setText("Resume");
        
    } else {
        if (btnStartPause.getText().equals("Start")) {
            try {
                int menit = Integer.parseInt(txtMenit.getText());
                int detik = Integer.parseInt(txtDetik.getText());
                totalDetik = (menit * 60) + detik;
                if (totalDetik <= 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                            "Input waktu harus lebih besar dari 0", 
                            "Error", 
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Input menit dan detik harus berupa angka!", 
                        "Error Input", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (totalDetik > 0) {
            timer.start();
            isRunning = true;
            btnStartPause.setText("Pause");
        }
    }
    }                                             

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        timer.stop();
    isRunning = false;
    btnStartPause.setText("Start");
    try {
        int menit = Integer.parseInt(txtMenit.getText().isEmpty() ? "0" : txtMenit.getText());
        int detik = Integer.parseInt(txtDetik.getText().isEmpty() ? "0" : txtDetik.getText());
        totalDetik = (menit * 60) + detik;
        
    } catch (NumberFormatException e) {
        totalDetik = 0;
        txtMenit.setText("0");
        txtDetik.setText("0");
    }
    updateTimerDisplay();
    }                                     

    private void txtMenitActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtDetikActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if (mainFormRef == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: Referensi ke MainForm tidak ditemukan!",
            "Error",
        javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (timer != null && timer.isRunning()) timer.stop();

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
        "Tugas selesai! Hapus dari daftar beserta deadlinenya?",
        "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {

        mainFormRef.hapusTugas(indexTugas);
        mainFormRef.hapusDeadline(indexTugas);
        
        mainFormRef.setVisible(true);
        this.dispose();
    }
                simpanData();  
                simpanDataDua();
    }                                          

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton back;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JButton btnStartPause;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTimerDisplay;
    private javax.swing.JLabel listtt;
    private javax.swing.JButton reset;
    private javax.swing.JLabel toDoList;
    private javax.swing.JTextField txtDetik;
    private javax.swing.JTextField txtMenit;
    // End of variables declaration                   

    private void simpanData() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void simpanDataDua() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
